### ISSUE TITLE
Fix plug.kak instructions in README

### ISSUE THREAD

**Issue by Kabouik** [sawdust-and-diamonds/scrollbar.kak#3]
I believe the plug.kak instructions should use the `sawdust-and-diamonds/scrollbar.kak` address instead of `kak-lsp/scrollbar.kak`.

Thanks for this nice plugin!

**Comment by sawdust-and-diamonds** [comment]
Oh God. Thanks for spotting that. Thanks and check out Screwtape's fork as well!

**Comment by sawdust-and-diamonds** [comment]
I've fixed this but forgot to reference it properly in the commit name. Thanks again though, anyway!
